### ISSUE TITLE
I have made a theme base on your theme design concepts on VSCode.

### ISSUE THREAD

**Issue by bennyxguo** [argyleink/Kung-Fury-Theme#4]
Hi Adam, I watched a lot of your youtube videos, as a theme aficionado and a web app UI designer, I just fall in love with your sublime3 theme Kung-Fury-Theme. I am a theme and UI designer working on [Auroral-UI](https://github.com/auroral-ui). 

I found your VSCode theme Kung-Fury-Theme, but sadly it isn't maintained. Therefore I had made a VSCode theme called [Aurora Future](https://github.com/auroral-ui/aurora-future-vscode-theme) base on the syntax highlighting you did in Kung-Fury.

Also added in the UI theming for VSCode to go with it and added in the advance syntax coloring rules base on yours. I also credit the theme idea on my documents. Hoping to have your permission for it. Thanks!

**Comment by argyleink** [comment]
thx for letting me know. it looks great! good luck with it!
